reviews = [
    "A pocket Rocket device. This Phone is a Beast but battery is trash. Bang for the Buck tho and i like the lens. Screen is decent. No comments about sensors. gaming lags at higher settings",
    "All good. Just the battery is too impressive. I've been using it for a bit over a year now.",
    "My purchase in June felt expensive because in the Amazon July sale, the iPhone was the only option available.",
    "I love the iPhone; I've been using it for the last few years.",
    "It's going to be months with this phone, and I am happy enough to have this powerful and premium device with me every day.",
    "Every feature, from a small to a big scale, is flawless, and I have a thing for the black color, which makes the phone look and feel even more premium.",
    "The battery life is great; mine goes for two days straight.",
    "I've been using it for almost a year, currently with the battery.",
    "It's a very good phone, and I got a good deal on Amazon. I personally picked it over the other option as there are hardly any differences between the two.",
    "The difference I felt is not worth paying additional. Overall, it does everything well that is expected of an iPhone.",
    "Good iPhone, not so good camera. I mean, don't doubt the camera as bad or worst; it's just that I didn't expect the camera to be, by default, wider than Samsung phones.",
    "And if I went to the max, it's the widest, I think, on a phone. So if you want to take wide shots, this is the phone; else, stick to Android, I would say.",
    "And did I mention how exciting the OS is? Man, you gotta use this OS if your life is too happening and you want to slow it down, pun intended. I'm saying this after using it for months now.",
    "The battery life was good before the updates; now it's meh.",
    "Great!",
    "Amazon delivered it to my village area, which was not expected, and the iPhone has been working fine since purchased.",
    "Really a great mobile with a perfect camera.",
    "THE PRODUCT IS ALL GOOD BUT THE PACKAGING.",
    "Incredible display. So eye-friendly. Flawless touch response. UI marvelous. Battery backup is good. Nothing more to say. Must buy.",
    "A very good phone, but the battery needs improvements.",
    "My first-ever iPhone.",
    "The product is genuine."
    "I took this phone in Feb after using it for a month. Almost good, but when it comes to the camera, a bit worse compared to android, not up to the mark. Even if you have a full network, you will not get a proper internet connection every time. The network gets up and down, and literally, you will get disappointed. Literally, my decision from shifting android to iPhone was a bit worse. I suggest sticking with android only.",
    "As an android fan switching to iPhone, I had a lot of issues initially. But once I got settled, it is kind of a perfect phone. Good performance and camera.",
    "The only phone, iPhone.",
    "After using almost a month, this phone is running smooth as a new one. There are some network issues with this phone, but overall, you can buy it.",
    "Good Battery Life, Good Quality, Good Performance.",
    "iPhone is very bad, no response from the company. I am sad.",
    "Man, undoubtedly the most satisfying phone on the planet.",
    "Good one.",
    "Worst.",
    "Writing this review after months. If planning to buy an iPhone, then purchase not because there are no major upgrades or variations. If your old phone is an iPhone, then you can upgrade to or OS is awesome. Best battery life compared to old versions. You can use it working day easily with charge. If a gamer, then you have to charge evening.",
    "Good condition of this product. But I'm liking this item.",
    "Good. We need to buy an adaptor separately; that's the drawback.",
    "Photos do not look good if not taken in daylight. Other than this, an awesome phone.",
    "I purchased iPhone red, the most powerful mobile in the world.",
    "Good but packing was normal for this premium phone.",
    "The phone is ok, but I strongly say that iPhone company is very small. Mind it to say because they have a good quality phone but they do not have an adaptor. Why customers go to another window or shop by another make; it will be available in the box with the phone.",
    "Value for status only.",
    "This is my first time using an Apple product, and I am happy. I switched from Android to iPhone worth the money. And I think there is no going back to Android for me.",
    "Awesome product, camera is very good, battery backup nice. Worth the cost.",
    "This is my first iPhone ever. I switched from Android after using it for many years to iPhone, and I can now say that I too have an iPhone. You can feel the emotions of mine. This is the best phone you'll ever have. Thank you.",
    "Everything is excellent.",
    "Overall good.",
    "Very nice attractive phone.",
    "It's working excellent, and I'm glad that I have received an Apple phone instead of getting soap.",
    "I am a first-time iPhone user, and in the beginning, I felt a bit awkward to use it. But after a few days, you will understand everything and will be used to it.",
    "It is perfect down to the last minute detail, flabbergasted by its smooth yet fast performance, and the camera is not up to the mark as or.",
    "Nothing.",
    "What can I tell about iPhone? You know everything.",
    "Apple has always tried to make premium devices, and iPhone is one of them, which has got an amazing processor and camera performance. One of the most liked things of iPhone by me is its privacy that is most concerned issues nowadays. I would strongly recommend going for iPhone.",
    "Without a charger, it looks dead.",
    "The media could not be loaded. Build Quality is far better than other competitors in the market, one of the best Smartphones under. As I switched from, so I miss the refresh rate in this Phone, but apart from that, everything works perfectly, especially Camera.",
    "Fast delivery, and packing was also good and safe.",
    "It's My First iPhone, and I was under the assumption for it to be a big deal to have one. Not upset with the purchase. Obviously proud to own one. Could have been better.",
    "Switching back to an iPhone, and I love it.",
    "Oh so pro, really I love it.",
    "Product is unserviceable within days and submitted at iCare.",
    "I bought it for my daughter, and she is really happy for it.",
    "iPhone is great, the service of Amazon is also quite good.",
    "Amazing camera, iPhone is iPhone. Deducted one star for being overpriced.",
    "Switched from Android to iPhone. Camera, battery are too good. High-security phone. Very smooth experience; installation processing is very fast. Apple processor is better than Android processors like Snapdragon. Don't think too much, just go for it.",
    "Dual sim functionality is not quite good in, and rest overall performance is good.",
    "Got it on an amazing deal. Phone is working well.",
    "Very comfortable for personal use.",
    "Good performance; must buy."
    "Bought it as a gift for my sister. First iPhone, and now I understand why Apple is a trillion-dollar company. There's just something about these products other companies fail to provide. From the smoothness of the UI to the touch and camera. It's really amazing.",
    "My iPhone, and proudly speaking that all of those are taken from only Amazon. Always got good deals from Amazon with genuine Apple products, and iPhone is always an iPhone.",
    "Happy with the purchase. Do not compare the screen size and price with Android ones.",
    "Super cool. Phone looks good; have a battery issue consuming a lot.",
    "Satisfied with the camera and overall performance of the phone (iPhone). Battery is amazing. Even better than the Android phones.",
    "Amazing phone with amazing features. And rest is you know, this is an iPhone.",
    "Very good mobile. New to iPhone fam, love it.",
    "iPhone has been a good experience on the eyes, apart from the other advantages that iPhone delivers as default.",
    "I'm a first-time iPhone user, not regretting the decision of switching from Android. iPhone just flows. Buy without any doubt. Delivery was poor though.",
    "Great purchase.",
    "Nice phone, but Amazon took days time to deliver.",
    "iPhone is iPhone, and it's really great. Smooth operations and works like butter.",
    "I appreciate them for using bubble wrap, but still, a corner of the iPhone box was chipped. Probability during shipping. But still, Amazon managed to deliver it without any hassle.",
    "This is my first experience switching from Android to iOS. But truly, it deserves the reputation. Thanks to Amazon for a safe and secure delivery.",
    "Recently bought iPhone. I was an Android user from the past; the phone is awesome, super but more expensive. Apple is not providing an adaptor for charge; this is the main drawback to the Apple company. If you are a first-time purchaser, you need to beg for an adaptor from others. This one thing I don't like from Apple, overall good.",
    "Bought this phone a month ago; good till now.",
    "iPhone has always worth the money. The moment you take this masterpiece in your hand, you know that you have invested your money for good. If you have more budget, go for pro or plus. Only issue was with Delivery executive and Amazon customer care.",
    "I'm a first-time user of an iPhone, and I can tell if you learn how to use it, then it is smooth as butter. The purple colour is so beautiful.",
    "Beautiful. Good vibes.",
    "Yes, sach Mai ek acche deal the aur product ko to kya kahe super.",
    "Like Siri, camera, security features, battery, one-hand operation, easily in pocket. Dislike the front camera setup, blocks a considerable amount of screen at the top.",
    "Product is good, but package quality is not good.",
    "Everything is good, but battery life degraded to 75% in just 6 months. Apple can do much better here. Apart from this, everything is good. Check out YouTube videos for performance, camera, and battery life.",
    "I got this phone for around 40000 rupees on the prime days sale on Amazon. I am extremely impressed and satisfied. The phone is very sleek and fast. I previously had an iPhone SE and am very satisfied with the upgrade. I also traded in the iPhone SE and got a very good rate. I would highly recommend.",
    "Very liked the phone.",
    "Good product at a good price.",
    "Good one.",
    "Brand Apple is the only word which doesn't need a review. Nice in segment with required salient features.",
    "Nice but camera not good.",
    "She needed a phone that has enough storage, speed, and experience using it.",
    "Amazon has given a genuine product; we trust any other than Amazon. Will recommend purchasing it from here only.",
    "Unlike and and has different chipsets.",
    "Fabulous.",
    "What a good product.",
    "It's genuine and works really well; thanks, Amazon.",
    "Love this product.",
    "I think I have to mention anything for this phone; this is the best smartphone ever.",
    "Good for low-end use.",
    "Product is good, as always, but this time delivery also very satisfying.",
    "Very nice product; colour is very sexy; very happy to get this.",
    "This is my 4th iPhone; have upgraded after using iPhone 6; love the phone. I use it for YouTube videos. You can check my channel for more details. It's called Anything.",
    "Great.",
    "Yes, this is a great phone; excellent.",
    "All the latest features available, and Apple iPhone are the best if you really looking for clarity in photos and hang-free life.",
    "Thanks Steve uncle, Ghey lord Tim uncle, and my sugar daddy Jeff uncle for a great deal in iPhone; everyone is offering for banging, rubbing on my...",
    "A little overpriced but worth the buy. Even though there is not much difference in the version or 12. But it just feels different every time. Totally recommended.",
    "Trustworthy. Go for it; as a first-time buyer, I was scared, but Amazon has nailed it. Amazing delivery; the security was just the best. Thank you, Amazon.",
    "IT'S GREAT. WORTH VALUE IPHONE.",
    "Genuine product. Prompt delivery. Competitive pricing by is a fantastic product and easy to adapt to from Android. Definitely a buy.",
    "Good deal and good service.",
    "Nice product and packaging.",
    "Amazing experience; a well-organised exchange with the latest phone.",
    "Everything is perfect.",
    "Undisputed leader in the smartphone market; no match of quality by any other company; great features; have enough storage.",
    "Cool and fast. Fast and on-time delivery.",
    "Gorgeous.",
    "The phone is just perfect, and the delivery came before time. The packaging was perfect too.",
    "No one can beat Apple products.",
    "Good quality product and value for money.",
    "Absolutely not comparable to any other.",
    "Some problem is screen top; different colours chainlike appear on the top of the screen.",
    "Battery backup is not awesome. Fingerprint sensor is perfect, but face lock is too slow. And you can use only 6 hours after one charge. So battery backup is not.",
    "Picked up the OnePlus during sale. As always, OnePlus is a good choice, plus the seller was prompt in sending the phone.",
    "It's good in terms of battery, screen quality, and gaming stuff. Not a heavy mobile gamer. Camera is OK. You have to take pics in 'Pro' mode always for better images. Not good for long distances; it pixelated the images even if you check it on mobile.",
    "Overall performance and functions are good. One star less as battery drains fast.",
    "I think little bit battery draining problem in the phone.",
    "All good in the phone, but it is having some bugs. Sometimes notifications get stacked up on the main screen, and sometimes swipe-up gesture doesn't work. But after a restart, it's all fine. I hope it gets resolved after a software update.",
    "Value for Money. My opinion: Go for it.",
    "Good mobile, only one problem when recording, that sound will be irritating, the beep has been recorded.",
    "I liked the mobile very much. Very good looks and also very much faster. This phone is value for money. But camera is not worthy for this price.",
    "6 hours screen on. No lag, no bugs till now. Front camera is best at day light. Fingerprint speed, speed, heating issues. After OxygenOS stable now, and camera is also good now.",
    "Mobile performance is awesome, but battery issues, draining very fast. It having 4500mAh battery but needs charging twice a day on average use.",
    "It's a good phone at this price range.",
    "Nice slim model, good looking, light weight, battery charger, quick charging, it helps 30 min for charging.",
    "Camera is not as perfect as it was in my previous OnePlus.",
    "Battery life is a bit low. Good phone for heavy duty.",
    "Good phone with a better camera setup, good performance, good features, good battery life. Good experience so far.",
    "Great Camera. The processor is too fast.",
    "Would've given a higher rating if the camera performance was better than the current one, especially in low light scenarios. Would appreciate if the battery backup can be improved slightly better than the current one. The build quality is commendable and has a sexy design overall.",
    "I am happy with the phone.",
    "Looking nice, better performance, and battery is normal.",
    "Performance is very good. But there is some heating issue while using the camera and at the time of charging specifically.",
    "Super phone, feel good.",
    "Very happy with OnePlus performance after using more than a week. Just go and buy this mobile; this device will not disappoint you. Fast phone till date.",
    "Very good mobile.",
    "Awesome work, go for it, picture in midnight nature.",
    "Overall a good phone but hard to find a tempered glass with curved phone, and battery life probably sucks, but fast charging makes up for it. I used this phone mostly on a work basis, so it gives a day worth of juice or more depends on my use.",
    "Battery problem. It is not at all a gaming mobile; it hangs a lot.",
    "At this price point, I loved what OnePlus is offering in 8. It feels absolutely premium. Primary camera is great and can do wonders. Loved the OS and its interface, minimal preloaded apps. I'm using 8GB Variant.",
    "Latest Processor. Amazing Primary Camera. Ultrafast charging.",
    "8GB RAM, Expandable, and 128GB ROM. Mobile is just working like butter smooth in every heavy task, beautiful Photography.",
    "Switching from a woefully beaten and battered phone, this one comes as a breath of fresh air. Charging is ultra-fast. Battery life is good. Very user-friendly. Great phone.",
    "Loved this phone. I bought this after experiencing 7T for three years. Excellent battery backup and super-fast charging. Beautiful camera quality. Super satisfied.",
    "Lagging with some apps like Amazon, etc.",
    "Getting too much lag while playing PUBG, and even if I choose SMOOTH version in PUBG. Rest all good. I can't recommend you if you are a PUBG player.",
    "My son has insisted me to buy OnePlus flagship phone; he is now very happy with its features which I could not understand in the last 3 years.",
    "The phone offers a fantastic balance between its price and how well it performs. Additionally, it has a strong and durable design along with long-lasting battery life.",
    "Loved the product and as described. Plus loved the quick delivery by Amazon. Thus, I am a regular customer here. Thank you, team.",
    "Using it near to a month, phone is working great. I used to be a Samsung fan before, but now OnePlus is good. UI is a lot different; Samsung is best in comparison to UI, but OnePlus is also not bad. Does everything what I need.",
    "I am writing this review after the use of 6 months. I was already using OnePlus mobile; quality of camera is awesome. Value for money.",
    "Phone build-up quality is nice, software also nice, but sometimes it is not satisfying our performance. Sometimes fingerprint sensor not responding; phone is very nice, sometimes it hangs down but very less time.",
    "Feel so happy; again I purchased OnePlus mobile. My 3T is now outdated. 12GB RAM; from last one week using this mobile, feel good. Whole day battery backup; quick charge.",
    "Camera zooming is like Rs 5,000 Mobile phone. One plus has to fix this issue. Rest things are excellent.",
    "Good camera, nice design, outstanding battery performance.",
    "Really best in class smartphone with great SD product. Best display and camera quality.",
    "Few cons: Speaker sound could be better. Camera/video quality is great, but still pics are not that great.",
    "Just got superb in the first glance. Let me use it now, and I will update.",
    "Mobile battery good. Fast charging (30 minutes charging). Good speed, display, photo quality very good.",
    "This phone is moderate and not justifying its price. When it gets slightly warm, then it drops frames in app opening. I use this without performance mode, still I faced this. This is repeatedly happening. No YouTuber says about this, so don't blindly follow any YouTuber. Camera is average, not up to mark for its price. Phone is not compact to handle this. Go for FE, it's a fabulous phone but low battery capacity. If you are ready to compromise this problem, then you can go for OnePlus. But OnePlus is more optimized and feels smooth.",
    "Pros: Good battery life. I got 7 hours of screen-on time. Clean UI, minimal bloatware. Good Haptic feedback. Good speakers. Satin finish to the glass back makes it feel premium. No variant with 6GB of RAM. The next upgrade is very expensive. Curved screen looks really beautiful and bright. Best screen in the segment. Back cover provided in the box is of good quality. Cons: Few bugs in UI. Hopefully will get resolved with an update. Ultra-wide and macro cameras are not good. Will keep updating the review over time.",
    "Phone is awesome, camera is good. Display is awesome.",
    "As usual, one more good phone from OnePlus. If you don't bother about the camera too much, just go for it. Quick Charging (less than 30 mins). Battery will not drain easily. If you are a normal user, you can use it for more than a day. If you are charging your phone leaving hotspot/wifi turned on, the phone will heat a little. Never experienced heating in other cases, even playing games and using multiple apps. Good phone. But don't buy without offers. It's a...",
    "Buy in offer with a discount on the phone.",
    "Best phone this year. I love it.",
    "Good camera, speed, and processor. Display is also good.",
    "Great camera quality, everything is good, but battery drains faster.",
    "Great performance. Premium design. Good battery life. Decent primary camera.",
    "So far no issues with the phone. Camera is really good.",
    "Phone is very fast and fluid, but battery life could have been better. It is draining too fast.",
    "Camera is average, battery life average, performance excellent, quick charging. Details not captured properly with the camera.",
    "It's one week I am using this phone. It's fast and runs all apps smoothly, but the battery life is not as it is being claimed. Claim is 48 hrs, but actually, you get only 24 hrs. It's value for money in this price. Good phone.",
    "Camera is good, phone processor is also awesome, and touch is working smooth. Battery life is great. Overall, the phone is awesome in this range. Go for it.",
    "Charging solo product, very nice.",
    "I liked the mobile, but the main thing is that the injection pin, USB cable, and other additional things are not there in the box.",
    "Mostly satisfied. Good product.",
    "Display not up to the mark. Processor also needs improvement. Software is pretty good.",
    "Review: Phone is light weight. I bought the light green color. It looks beautiful.",
]
