from detection_modules.preprocessing import (
    process_text_conjunctions_demonstration,
    tokenize_words,
    stem_token,
    clean_text,
    clean_array,
)


def find_reviews_wrt_aspects(aspect, sentence, nlp):
    purchased_keywords = [
        "bought",
        "purchased",
        "ordered",
        "acquired",
        "got",
        "obtained",
        "picked",
        "selected",
        "chose",
        "decided",
        "gathered",
        "gifted",
        "new",
        "latest",
    ]

    age_keywords = [
        "old",
        "new",
        "fresh",
        "latest",
        "current",
        "up-to-date",
        "modern",
        "contemporary",
        "recently released",
        "state-of-the-art",
        "cutting-edge",
        "latest technology",
        "newest model/version",
        "released",
        "recently launched",
        "years",
        "qwerty",
        "analog",
        "vintage",
        "outdated",
        "retro",
        "recent",
        "out-of-date",
        "ancient",
        "modern",
        "obsolete",
    ]

    performance_keywords = [
        "perform",
        "performance",
        "work",
        "work well",
        "work efficiently",
        "function",
        "functionality",
        "operate",
        "run",
        "execute",
        "Smooth",
        "Snappy",
        "fast",
        "responsive",
        "reliable",
        "efficient",
        "dynamic",
        "beast",
    ]

    design_keywords = [
        "design",
        "appearance",
        "look",
        "style",
        "shape",
        "form",
        "structure",
        "outline",
        "configuration",
        "sleek",
        "beautiful",
        "elegant",
        "stylish",
        "minimalistic",
        "attractive",
        "eyecatching",
        "futuristic",
        "classy",
        "slim",
        "compact",
        "aesthetic",
        "comfortable ",
    ]

    screen_keywords = [
        "screen",
        "display",
        "monitor",
        "view",
        "picture",
        "image",
        "resolution",
        "size",
        "ratio",
        "brightness",
        "contrast",
        "pixel",
        "color",
        "viewing",
        "amoled",
        "lcd",
        "oled",
        "refresh rate",
        "bezel",
        "hdr",
        "notch",
        "protector",
        "clear",
        "sharp",
        "vivid",
        "bright",
        "dim",
        "dull",
        "high-resolution",
        "low-resolution",
        "color-rich",
        "anti-galre" "color-accurate",
        "wide-angle",
        "eye-friendly",
        "narrow-angle",
        "responsive",
        "smooth",
        "fast",
        "slow",
        "immersive",
        "reflective",
        "glare-free",
        "huge",
    ]

    interactability_keywords = [
        "touch",
        "touchscreen",
        "haptic",
        "scrolling",
        "UI",
        "gesture",
        "multi-touch",
        "stylus",
        "feedback",
        "interactable",
        "responsiveness" "interactive",
        "responsive",
        "lag",
        "smooth operator",
    ]

    battery_keywords = [
        "battery",
        "power",
        "energy",
        "charge",
        "duration",
        "life",
        "capacity",
        "runtime",
        "endurance",
        "lasting",
        "dead",
        "capacity",
        "usage",
        "drain",
        "charging time",
        "charging",
        "wireless",
        "health",
        "saver mode",
        "backup",
        "consumption",
        "charging port",
        "endurance",
        "long-lasting",
        "efficient",
        "reliable",
        "powerful",
        "fast-charging",
        "wireless",
        "low-power",
        "durable",
        "energy-saving",
        "sustainable",
        "eco-friendly",
        "dependable",
    ]
    brand_keywords = [
        "brand",
        "manufacturer",
        "make",
        "producer",
        "label",
        "logo",
        "identity",
        "reputation",
        "status",
        "name",
        "popularity",
        "market share",
        "innovation",
        "customer support",
        "product lineup",
        "availability",
        "connectivity",
        "accessories",
        "warranty",
        "popular",
        "reliable",
        "innovative",
        "iconic",
        "trusted",
        "sophisticated",
        "highquality",
        "technologically advanced",
        "user-friendly",
        "cutting-edge",
        "durable",
        "versatile",
        "efficient",
        "longlasting",
        "advanced",
        "competitive",
        "iphone",
        "android",
        "samsung" "mi",
        "xiaomi",
        "google",
    ]

    cost_keywords = [
        "price",
        "cost",
        "value",
        "worth",
        "expense",
        "payment",
        "amount",
        "fee",
        "charge",
        "budget",
        "sale",
        "low-end",
        "mid-range",
        "high-end",
        "expensive",
        "affordable",
        "costly",
        "reasonable",
        "budgetfriendly",
        "pricey",
        "inexpensive",
        "valuable",
        "cheap",
        "economical",
        "highpriced",
        "overpriced",
        "premium",
        "discounted",
        "competitive",
        "worthwhile",
        "over-budget",
        "extravagant",
        "low-cost",
        "pocketfriendly",
        "bang for the buck",
    ]

    camera_keywords = [
        "cameras",
        "photography",
        "lens",
        "shot",
        "picture",
        "image",
        "snapshot",
        "focus",
        "flash",
        "resolution",
        "aperture",
        "zoom",
        "megapixel",
        "autofocus",
        "shutter",
        "stabilization",
        "hdr",
        "lowlight",
        "depth perception",
        "selfie",
        "video",
        "motion",
        "mode",
        "panorama",
        "telephoto",
        "ultrawide",
        "night mode",
        "macro",
        "bokeh",
        "clear",
        "sharp",
        "detailed",
        "vivid",
        "bright",
        "colorful",
        "fast",
        "accurate",
        "low noise",
        "crisp",
        "dynamic",
        "balanced",
        "professional",
        "artistic",
        "smooth",
        "consistent",
        "stunning",
        "natural",
    ]

    os_keywords = [
        "operating system" "android",
        "ios",
        "windows",
        "windows",
        "Kaios",
        "harmonyos",
        "lineage os",
        "oxygen os",
        "oxygen",
        "miui",
        "color os",
        "color",
        "realme ui",
        "interface",
        "customization",
        "compatibility",
        "security",
        "stability",
        "updates",
        "integration",
        "navigation",
        "multitasking",
        "accessibility",
        "functionality",
        "efficiency",
        "control",
        "interface",
        "operating system version",
        "compatibility",
        "ai",
        "intuitive",
        "efficient",
        "customizable",
        "seamless",
        "secure",
        "reliable",
        "stable",
        "fast",
        "responsive",
        "user",
        "robust",
        "versatile",
        "innovative",
        "modern",
        "streamlined",
        "fluid",
        "dynamic",
        "adaptive",
        "consistent",
    ]

    experience_keywords = [
        "experience",
        "feeling",
        "impression",
        "perception",
        "sensation",
        "judgment",
        "opinion",
        "attitude",
        "reaction",
        "view",
        "memorable",
        "pleasant",
        "unforgettable",
        "challenging",
        "exciting",
        "educational",
        "unique",
        "incredible",
        "fulfilling",
        "inspiring",
        "refreshing",
        "empowering",
        "eyeopening",
        "rewarding",
        "intense",
        "engaging",
        "transformative",
        "relaxing",
        "disappointing",
        "frustrating",
        "superb",
    ]

    phone_keywords = [
        "phone",
        "smartphone",
        "cell",
        "device",
        "handset" "awesome",
        "good" "fantastic",
        "cool",
        "superb",
        "perfect",
        "bad",
        "trash",
        "worst",
        "lit",
        "goat",
        "op",
    ]

    aspect_keywords = {
        "camera": camera_keywords,
        "performance": performance_keywords,
        "design": design_keywords,
        "screen": screen_keywords,
        "interactibility": interactability_keywords,
        "battery": battery_keywords,
        "brand": brand_keywords,
        "cost": cost_keywords,
        "os": os_keywords,
        "experience": experience_keywords,
        "phone": phone_keywords,
        "age": age_keywords,
        "purchased": purchased_keywords,
    }

    if any(
        stem_token(element) in sentence.lower().split()
        for element in aspect_keywords[aspect.lower()]
    ):
        return sentence
